sudo: false

language: python

python:
  # - 2.7
  - 3.4
  - 3.5
  - 3.6
  - nightly

env:
  - TRAVIS=1

install:
  - pip install -r requirements.txt
  - pip install --upgrade git+git://github.com/seemethere/nba_py.git@ffeaf4251d796ff9313367a752a45a0d7b16489e

script:
  - cd nba_stats/ && python -m unittest discover
